version: "3.8"

services:
    backend:
        build: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend/app:/app
    frontend:
        build: ./frontend
        ports:
            - "5000:5000"
        command: ["npx", "serve", "-s", "public"]
